theme: minima
title: Hey there!
author: Abi
email: abhigrace@gmail.com
description: > # this means to ignore newlines until "baseurl:"
I am an Undergraduate Software Engineering student at SLIIT. I am currently working as a intern at ELZIAN AGRO. 

# social links
twitter_username: your-abhigrace-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-Abiramy-R-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
